name: e2ecleanup
run-name: Delete the organization in Tower created for e2e testing
# This workflow can be triggered manually with GitHub actions workflow dispatch button.
# It will automate the end-to-end creation all of the following entities in Nextflow Tower.

on:
  workflow_dispatch:
  pull_request:

jobs:
  e2e-testing:
    name:
    if: github.repository == 'seqeralabs/tw-pywrap'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}
    env:
      TOWER_ACCESS_TOKEN: ${{ secrets.TOWER_ACCESS_TOKEN }}
      TOWER_GITHUB_PASSWORD: ${{ secrets.TOWER_GITHUB_PASSWORD }}
    steps:
      - name: Check out source-code repository
        uses: actions/checkout@v3

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2.2.0
        with:
          auto-update-conda: true
          environment-file: environment.yml
          miniforge-variant: Mambaforge
          miniforge-version: latest
          python-version: '3.10'
          activate-environment: tw-pywrap
          use-mamba: true

      - name: Install pip & tw-pywrap
        run: |
          mamba install -y -c conda-forge pip
          pip install -e .

      - name: Delete e2e test organization
        run: |
          mamba init
          python examples/python/cleanup_e2e.py
